/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { LoganVantaCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

/**
 * List vulnerabilities within the scope of a given audit
 *
 * @remarks
 * List all vulnerabilities based on selected filters.
 */
export async function auditsListVulnerabilities(
  client: LoganVantaCore,
  request: operations.ListVulnerabilitiesRequest,
  options?: RequestOptions,
): Promise<
  Result<
    components.PaginatedResponseVulnerability,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const parsed = safeParse(
    request,
    (value) =>
      operations.ListVulnerabilitiesRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return parsed;
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    auditId: encodeSimple("auditId", payload.auditId, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/audits/{auditId}/vulnerabilities")(pathParams);

  const query = encodeFormQuery({
    "externalVulnerabilityId": payload.externalVulnerabilityId,
    "includeVulnerabilitiesWithoutSlas":
      payload.includeVulnerabilitiesWithoutSlas,
    "integrationId": payload.integrationId,
    "isDeactivated": payload.isDeactivated,
    "isFixAvailable": payload.isFixAvailable,
    "packageIdentifier": payload.packageIdentifier,
    "pageCursor": payload.pageCursor,
    "pageSize": payload.pageSize,
    "query": payload.query,
    "severity": payload.severity,
    "slaDeadlineAfterDate": payload.slaDeadlineAfterDate,
    "slaDeadlineBeforeDate": payload.slaDeadlineBeforeDate,
    "vulnerableAssetId": payload.vulnerableAssetId,
  });

  const headers = new Headers({
    Accept: "application/json",
  });

  const secConfig = await extractSecurity(client._options.bearerAuth);
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    operationID: "ListVulnerabilities",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const [result] = await M.match<
    components.PaginatedResponseVulnerability,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, components.PaginatedResponseVulnerability$inboundSchema),
    M.fail(["4XX", "5XX"]),
  )(response);
  if (!result.ok) {
    return result;
  }

  return result;
}
