/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditorsCreateAuditor } from "../funcs/auditorsCreateAuditor.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auditors extends ClientSDK {
  /**
   * Create an auditor
   *
   * @remarks
   * Create an auditor in Vanta.
   */
  async createAuditor(
    request: components.AddAuditorInput,
    options?: RequestOptions,
  ): Promise<components.Auditor> {
    return unwrapAsync(auditorsCreateAuditor(
      this,
      request,
      options,
    ));
  }
}
