/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auditors } from "./auditors.js";
import { Audits } from "./audits.js";

export class LoganVanta extends ClientSDK {
  private _audits?: Audits;
  get audits(): Audits {
    return (this._audits ??= new Audits(this._options));
  }

  private _auditors?: Auditors;
  get auditors(): Auditors {
    return (this._auditors ??= new Auditors(this._options));
  }
}
