/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditCommentsRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Includes all comments that have changed since changedSinceDate.
   */
  changedSinceDate?: Date | undefined;
};

/** @internal */
export const ListAuditCommentsRequest$inboundSchema: z.ZodType<
  ListAuditCommentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
});

/** @internal */
export type ListAuditCommentsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
};

/** @internal */
export const ListAuditCommentsRequest$outboundSchema: z.ZodType<
  ListAuditCommentsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditCommentsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditCommentsRequest$ {
  /** @deprecated use `ListAuditCommentsRequest$inboundSchema` instead. */
  export const inboundSchema = ListAuditCommentsRequest$inboundSchema;
  /** @deprecated use `ListAuditCommentsRequest$outboundSchema` instead. */
  export const outboundSchema = ListAuditCommentsRequest$outboundSchema;
  /** @deprecated use `ListAuditCommentsRequest$Outbound` instead. */
  export type Outbound = ListAuditCommentsRequest$Outbound;
}

export function listAuditCommentsRequestToJSON(
  listAuditCommentsRequest: ListAuditCommentsRequest,
): string {
  return JSON.stringify(
    ListAuditCommentsRequest$outboundSchema.parse(listAuditCommentsRequest),
  );
}

export function listAuditCommentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditCommentsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditCommentsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditCommentsRequest' from JSON`,
  );
}
