/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditEvidenceRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Includes all audit evidence that have changed since changedSinceDate.
   */
  changedSinceDate?: Date | undefined;
};

/** @internal */
export const ListAuditEvidenceRequest$inboundSchema: z.ZodType<
  ListAuditEvidenceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
});

/** @internal */
export type ListAuditEvidenceRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
};

/** @internal */
export const ListAuditEvidenceRequest$outboundSchema: z.ZodType<
  ListAuditEvidenceRequest$Outbound,
  z.ZodTypeDef,
  ListAuditEvidenceRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditEvidenceRequest$ {
  /** @deprecated use `ListAuditEvidenceRequest$inboundSchema` instead. */
  export const inboundSchema = ListAuditEvidenceRequest$inboundSchema;
  /** @deprecated use `ListAuditEvidenceRequest$outboundSchema` instead. */
  export const outboundSchema = ListAuditEvidenceRequest$outboundSchema;
  /** @deprecated use `ListAuditEvidenceRequest$Outbound` instead. */
  export type Outbound = ListAuditEvidenceRequest$Outbound;
}

export function listAuditEvidenceRequestToJSON(
  listAuditEvidenceRequest: ListAuditEvidenceRequest,
): string {
  return JSON.stringify(
    ListAuditEvidenceRequest$outboundSchema.parse(listAuditEvidenceRequest),
  );
}

export function listAuditEvidenceRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditEvidenceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditEvidenceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditEvidenceRequest' from JSON`,
  );
}
