/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ControlDomain = {
  ARTIFICIALAndAUTONOMOUSTECHNOLOGY: "ARTIFICIAL_&_AUTONOMOUS_TECHNOLOGY",
  AssetManagement: "ASSET_MANAGEMENT",
  BUSINESSCONTINUITYAndDISASTERRECOVERY:
    "BUSINESS_CONTINUITY_&_DISASTER_RECOVERY",
  CAPACITYAndPERFORMANCEPLANNING: "CAPACITY_&_PERFORMANCE_PLANNING",
  ChangeManagement: "CHANGE_MANAGEMENT",
  CloudSecurity: "CLOUD_SECURITY",
  Compliance: "COMPLIANCE",
  ConfigurationManagement: "CONFIGURATION_MANAGEMENT",
  ContinuousMonitoring: "CONTINUOUS_MONITORING",
  CryptographicProtections: "CRYPTOGRAPHIC_PROTECTIONS",
  DATACLASSIFICATIONAndHANDLING: "DATA_CLASSIFICATION_&_HANDLING",
  EmbeddedTechnology: "EMBEDDED_TECHNOLOGY",
  EndpointSecurity: "ENDPOINT_SECURITY",
  HumanResourcesSecurity: "HUMAN_RESOURCES_SECURITY",
  IDENTIFICATIONAndAUTHENTICATION: "IDENTIFICATION_&_AUTHENTICATION",
  IncidentResponse: "INCIDENT_RESPONSE",
  InformationAssurance: "INFORMATION_ASSURANCE",
  Maintenance: "MAINTENANCE",
  MobileDeviceManagement: "MOBILE_DEVICE_MANAGEMENT",
  NetworkSecurity: "NETWORK SECURITY",
  PHYSICALAndENVIRONMENTALSECURITY: "PHYSICAL_&_ENVIRONMENTAL_SECURITY",
  Privacy: "PRIVACY",
  PROJECTAndRESOURCEMANAGEMENT: "PROJECT_&_RESOURCE MANAGEMENT",
  RiskManagement: "RISK_MANAGEMENT",
  SECUREENGINEERINGAndARCHITECTURE: "SECURE_ENGINEERING_&_ARCHITECTURE",
  SECURITYAWARENESSAndTRAINING: "SECURITY_AWARENESS_&_TRAINING",
  SecurityOperations: "SECURITY_OPERATIONS",
  SECURITYAndPRIVACYGOVERNANCE: "SECURITY_&_PRIVACY_GOVERNANCE",
  TECHNOLOGYDEVELOPMENTAndACQUISITION: "TECHNOLOGY_DEVELOPMENT_&_ACQUISITION",
  ThirdPartyManagement: "THIRD-PARTY_MANAGEMENT",
  ThreatManagement: "THREAT_MANAGEMENT",
  VULNERABILITYAndPATCHMANAGEMENT: "VULNERABILITY_&_PATCH_MANAGEMENT",
  WebSecurity: "WEB_SECURITY",
  Administrative: "ADMINISTRATIVE",
  Physical: "PHYSICAL",
  Technical: "TECHNICAL",
  Basic: "BASIC",
  Derived: "DERIVED",
} as const;
export type ControlDomain = ClosedEnum<typeof ControlDomain>;

/** @internal */
export const ControlDomain$inboundSchema: z.ZodNativeEnum<
  typeof ControlDomain
> = z.nativeEnum(ControlDomain);

/** @internal */
export const ControlDomain$outboundSchema: z.ZodNativeEnum<
  typeof ControlDomain
> = ControlDomain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ControlDomain$ {
  /** @deprecated use `ControlDomain$inboundSchema` instead. */
  export const inboundSchema = ControlDomain$inboundSchema;
  /** @deprecated use `ControlDomain$outboundSchema` instead. */
  export const outboundSchema = ControlDomain$outboundSchema;
}
