/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RecurrenceDuration,
  RecurrenceDuration$inboundSchema,
  RecurrenceDuration$outboundSchema,
} from "./recurrenceduration.js";

export type CreateCustomEvidenceRequestInput = {
  /**
   * A set of controls, referenced by id, to map the evidence to
   */
  controlIds: Array<string>;
  /**
   * Title for the evidence request
   */
  title: string;
  /**
   * Description for the evidence request
   */
  description: string;
  cadence: RecurrenceDuration;
  reminderWindow: RecurrenceDuration;
  /**
   * Whether this document contains sensitive data and needs more restrictive read access
   */
  isRestricted: boolean;
  /**
   * Email of the auditor who created the custom evidence request.
   */
  auditorEmail: string;
};

/** @internal */
export const CreateCustomEvidenceRequestInput$inboundSchema: z.ZodType<
  CreateCustomEvidenceRequestInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  controlIds: z.array(z.string()),
  title: z.string(),
  description: z.string(),
  cadence: RecurrenceDuration$inboundSchema,
  reminderWindow: RecurrenceDuration$inboundSchema,
  isRestricted: z.boolean(),
  auditorEmail: z.string(),
});

/** @internal */
export type CreateCustomEvidenceRequestInput$Outbound = {
  controlIds: Array<string>;
  title: string;
  description: string;
  cadence: string;
  reminderWindow: string;
  isRestricted: boolean;
  auditorEmail: string;
};

/** @internal */
export const CreateCustomEvidenceRequestInput$outboundSchema: z.ZodType<
  CreateCustomEvidenceRequestInput$Outbound,
  z.ZodTypeDef,
  CreateCustomEvidenceRequestInput
> = z.object({
  controlIds: z.array(z.string()),
  title: z.string(),
  description: z.string(),
  cadence: RecurrenceDuration$outboundSchema,
  reminderWindow: RecurrenceDuration$outboundSchema,
  isRestricted: z.boolean(),
  auditorEmail: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateCustomEvidenceRequestInput$ {
  /** @deprecated use `CreateCustomEvidenceRequestInput$inboundSchema` instead. */
  export const inboundSchema = CreateCustomEvidenceRequestInput$inboundSchema;
  /** @deprecated use `CreateCustomEvidenceRequestInput$outboundSchema` instead. */
  export const outboundSchema = CreateCustomEvidenceRequestInput$outboundSchema;
  /** @deprecated use `CreateCustomEvidenceRequestInput$Outbound` instead. */
  export type Outbound = CreateCustomEvidenceRequestInput$Outbound;
}

export function createCustomEvidenceRequestInputToJSON(
  createCustomEvidenceRequestInput: CreateCustomEvidenceRequestInput,
): string {
  return JSON.stringify(
    CreateCustomEvidenceRequestInput$outboundSchema.parse(
      createCustomEvidenceRequestInput,
    ),
  );
}

export function createCustomEvidenceRequestInputFromJSON(
  jsonString: string,
): SafeParseResult<CreateCustomEvidenceRequestInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCustomEvidenceRequestInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCustomEvidenceRequestInput' from JSON`,
  );
}
