/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A custom task.
 */
export type CustomTask = {
  name: string;
};

/** @internal */
export const CustomTask$inboundSchema: z.ZodType<
  CustomTask,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type CustomTask$Outbound = {
  name: string;
};

/** @internal */
export const CustomTask$outboundSchema: z.ZodType<
  CustomTask$Outbound,
  z.ZodTypeDef,
  CustomTask
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomTask$ {
  /** @deprecated use `CustomTask$inboundSchema` instead. */
  export const inboundSchema = CustomTask$inboundSchema;
  /** @deprecated use `CustomTask$outboundSchema` instead. */
  export const outboundSchema = CustomTask$outboundSchema;
  /** @deprecated use `CustomTask$Outbound` instead. */
  export type Outbound = CustomTask$Outbound;
}

export function customTaskToJSON(customTask: CustomTask): string {
  return JSON.stringify(CustomTask$outboundSchema.parse(customTask));
}

export function customTaskFromJSON(
  jsonString: string,
): SafeParseResult<CustomTask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomTask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomTask' from JSON`,
  );
}
