/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TaskStatus,
  TaskStatus$inboundSchema,
  TaskStatus$outboundSchema,
} from "./taskstatus.js";
import {
  TaskTypeINSTALLDEVICEMONITORING,
  TaskTypeINSTALLDEVICEMONITORING$inboundSchema,
  TaskTypeINSTALLDEVICEMONITORING$outboundSchema,
} from "./tasktypeinstalldevicemonitoring.js";

/**
 * If the task is disabled, the reason and date when it was disabled.
 */
export type InstallDeviceMonitoringTaskSummaryDisabled = {
  date: Date;
  reason: string | null;
};

/**
 * Task summary for installing device monitoring.
 */
export type InstallDeviceMonitoringTaskSummary = {
  taskType: TaskTypeINSTALLDEVICEMONITORING;
  /**
   * The status of a task.
   *
   * @remarks
   * - COMPLETE: The task has been completed.
   * - DUE_SOON: The task is due soon.
   * - OVERDUE: The task is overdue.
   * - NONE: The task is not assigned.
   */
  status: TaskStatus;
  /**
   * The due date of the task.
   */
  dueDate: Date | null;
  /**
   * The date the task was completed.
   */
  completionDate: Date | null;
  /**
   * If the task is disabled, the reason and date when it was disabled.
   */
  disabled: InstallDeviceMonitoringTaskSummaryDisabled | null;
};

/** @internal */
export const InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema:
  z.ZodType<InstallDeviceMonitoringTaskSummaryDisabled, z.ZodTypeDef, unknown> =
    z.object({
      date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
      reason: z.nullable(z.string()),
    });

/** @internal */
export type InstallDeviceMonitoringTaskSummaryDisabled$Outbound = {
  date: string;
  reason: string | null;
};

/** @internal */
export const InstallDeviceMonitoringTaskSummaryDisabled$outboundSchema:
  z.ZodType<
    InstallDeviceMonitoringTaskSummaryDisabled$Outbound,
    z.ZodTypeDef,
    InstallDeviceMonitoringTaskSummaryDisabled
  > = z.object({
    date: z.date().transform(v => v.toISOString()),
    reason: z.nullable(z.string()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallDeviceMonitoringTaskSummaryDisabled$ {
  /** @deprecated use `InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema` instead. */
  export const inboundSchema =
    InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema;
  /** @deprecated use `InstallDeviceMonitoringTaskSummaryDisabled$outboundSchema` instead. */
  export const outboundSchema =
    InstallDeviceMonitoringTaskSummaryDisabled$outboundSchema;
  /** @deprecated use `InstallDeviceMonitoringTaskSummaryDisabled$Outbound` instead. */
  export type Outbound = InstallDeviceMonitoringTaskSummaryDisabled$Outbound;
}

export function installDeviceMonitoringTaskSummaryDisabledToJSON(
  installDeviceMonitoringTaskSummaryDisabled:
    InstallDeviceMonitoringTaskSummaryDisabled,
): string {
  return JSON.stringify(
    InstallDeviceMonitoringTaskSummaryDisabled$outboundSchema.parse(
      installDeviceMonitoringTaskSummaryDisabled,
    ),
  );
}

export function installDeviceMonitoringTaskSummaryDisabledFromJSON(
  jsonString: string,
): SafeParseResult<
  InstallDeviceMonitoringTaskSummaryDisabled,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'InstallDeviceMonitoringTaskSummaryDisabled' from JSON`,
  );
}

/** @internal */
export const InstallDeviceMonitoringTaskSummary$inboundSchema: z.ZodType<
  InstallDeviceMonitoringTaskSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  taskType: TaskTypeINSTALLDEVICEMONITORING$inboundSchema,
  status: TaskStatus$inboundSchema,
  dueDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  completionDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  disabled: z.nullable(
    z.lazy(() => InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema),
  ),
});

/** @internal */
export type InstallDeviceMonitoringTaskSummary$Outbound = {
  taskType: string;
  status: string;
  dueDate: string | null;
  completionDate: string | null;
  disabled: InstallDeviceMonitoringTaskSummaryDisabled$Outbound | null;
};

/** @internal */
export const InstallDeviceMonitoringTaskSummary$outboundSchema: z.ZodType<
  InstallDeviceMonitoringTaskSummary$Outbound,
  z.ZodTypeDef,
  InstallDeviceMonitoringTaskSummary
> = z.object({
  taskType: TaskTypeINSTALLDEVICEMONITORING$outboundSchema,
  status: TaskStatus$outboundSchema,
  dueDate: z.nullable(z.date().transform(v => v.toISOString())),
  completionDate: z.nullable(z.date().transform(v => v.toISOString())),
  disabled: z.nullable(
    z.lazy(() => InstallDeviceMonitoringTaskSummaryDisabled$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallDeviceMonitoringTaskSummary$ {
  /** @deprecated use `InstallDeviceMonitoringTaskSummary$inboundSchema` instead. */
  export const inboundSchema = InstallDeviceMonitoringTaskSummary$inboundSchema;
  /** @deprecated use `InstallDeviceMonitoringTaskSummary$outboundSchema` instead. */
  export const outboundSchema =
    InstallDeviceMonitoringTaskSummary$outboundSchema;
  /** @deprecated use `InstallDeviceMonitoringTaskSummary$Outbound` instead. */
  export type Outbound = InstallDeviceMonitoringTaskSummary$Outbound;
}

export function installDeviceMonitoringTaskSummaryToJSON(
  installDeviceMonitoringTaskSummary: InstallDeviceMonitoringTaskSummary,
): string {
  return JSON.stringify(
    InstallDeviceMonitoringTaskSummary$outboundSchema.parse(
      installDeviceMonitoringTaskSummary,
    ),
  );
}

export function installDeviceMonitoringTaskSummaryFromJSON(
  jsonString: string,
): SafeParseResult<InstallDeviceMonitoringTaskSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InstallDeviceMonitoringTaskSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallDeviceMonitoringTaskSummary' from JSON`,
  );
}
