/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * User can be active or upcoming leave period
 */
export const LeaveStatus = {
  Active: "ACTIVE",
  Upcoming: "UPCOMING",
} as const;
/**
 * User can be active or upcoming leave period
 */
export type LeaveStatus = ClosedEnum<typeof LeaveStatus>;

/** @internal */
export const LeaveStatus$inboundSchema: z.ZodNativeEnum<typeof LeaveStatus> = z
  .nativeEnum(LeaveStatus);

/** @internal */
export const LeaveStatus$outboundSchema: z.ZodNativeEnum<typeof LeaveStatus> =
  LeaveStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LeaveStatus$ {
  /** @deprecated use `LeaveStatus$inboundSchema` instead. */
  export const inboundSchema = LeaveStatus$inboundSchema;
  /** @deprecated use `LeaveStatus$outboundSchema` instead. */
  export const outboundSchema = LeaveStatus$outboundSchema;
}
