/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PersonInfoSourceTypeINTEGRATION = {
  Integration: "INTEGRATION",
} as const;
export type PersonInfoSourceTypeINTEGRATION = ClosedEnum<
  typeof PersonInfoSourceTypeINTEGRATION
>;

/** @internal */
export const PersonInfoSourceTypeINTEGRATION$inboundSchema: z.ZodNativeEnum<
  typeof PersonInfoSourceTypeINTEGRATION
> = z.nativeEnum(PersonInfoSourceTypeINTEGRATION);

/** @internal */
export const PersonInfoSourceTypeINTEGRATION$outboundSchema: z.ZodNativeEnum<
  typeof PersonInfoSourceTypeINTEGRATION
> = PersonInfoSourceTypeINTEGRATION$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PersonInfoSourceTypeINTEGRATION$ {
  /** @deprecated use `PersonInfoSourceTypeINTEGRATION$inboundSchema` instead. */
  export const inboundSchema = PersonInfoSourceTypeINTEGRATION$inboundSchema;
  /** @deprecated use `PersonInfoSourceTypeINTEGRATION$outboundSchema` instead. */
  export const outboundSchema = PersonInfoSourceTypeINTEGRATION$outboundSchema;
}
