/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PersonInfoSourceTypeVANTA = {
  Vanta: "VANTA",
} as const;
export type PersonInfoSourceTypeVANTA = ClosedEnum<
  typeof PersonInfoSourceTypeVANTA
>;

/** @internal */
export const PersonInfoSourceTypeVANTA$inboundSchema: z.ZodNativeEnum<
  typeof PersonInfoSourceTypeVANTA
> = z.nativeEnum(PersonInfoSourceTypeVANTA);

/** @internal */
export const PersonInfoSourceTypeVANTA$outboundSchema: z.ZodNativeEnum<
  typeof PersonInfoSourceTypeVANTA
> = PersonInfoSourceTypeVANTA$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PersonInfoSourceTypeVANTA$ {
  /** @deprecated use `PersonInfoSourceTypeVANTA$inboundSchema` instead. */
  export const inboundSchema = PersonInfoSourceTypeVANTA$inboundSchema;
  /** @deprecated use `PersonInfoSourceTypeVANTA$outboundSchema` instead. */
  export const outboundSchema = PersonInfoSourceTypeVANTA$outboundSchema;
}
