/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS = {
  CompleteCustomOffboardingTasks: "COMPLETE_CUSTOM_OFFBOARDING_TASKS",
} as const;
export type TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS = ClosedEnum<
  typeof TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS
>;

/** @internal */
export const TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$inboundSchema:
  z.ZodNativeEnum<typeof TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS> = z.nativeEnum(
    TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS,
  );

/** @internal */
export const TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$outboundSchema:
  z.ZodNativeEnum<typeof TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS> =
    TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$ {
  /** @deprecated use `TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$inboundSchema` instead. */
  export const inboundSchema =
    TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$inboundSchema;
  /** @deprecated use `TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$outboundSchema` instead. */
  export const outboundSchema =
    TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS$outboundSchema;
}
