/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeCOMPLETETRAININGS = {
  CompleteTrainings: "COMPLETE_TRAININGS",
} as const;
export type TaskTypeCOMPLETETRAININGS = ClosedEnum<
  typeof TaskTypeCOMPLETETRAININGS
>;

/** @internal */
export const TaskTypeCOMPLETETRAININGS$inboundSchema: z.ZodNativeEnum<
  typeof TaskTypeCOMPLETETRAININGS
> = z.nativeEnum(TaskTypeCOMPLETETRAININGS);

/** @internal */
export const TaskTypeCOMPLETETRAININGS$outboundSchema: z.ZodNativeEnum<
  typeof TaskTypeCOMPLETETRAININGS
> = TaskTypeCOMPLETETRAININGS$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskTypeCOMPLETETRAININGS$ {
  /** @deprecated use `TaskTypeCOMPLETETRAININGS$inboundSchema` instead. */
  export const inboundSchema = TaskTypeCOMPLETETRAININGS$inboundSchema;
  /** @deprecated use `TaskTypeCOMPLETETRAININGS$outboundSchema` instead. */
  export const outboundSchema = TaskTypeCOMPLETETRAININGS$outboundSchema;
}
