/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeCOMPLETECUSTOMTASKS = {
  CompleteCustomTasks: "COMPLETE_CUSTOM_TASKS",
} as const;
export type TaskTypeCOMPLETECUSTOMTASKS = ClosedEnum<
  typeof TaskTypeCOMPLETECUSTOMTASKS
>;

/** @internal */
export const TaskTypeCOMPLETECUSTOMTASKS$inboundSchema: z.ZodNativeEnum<
  typeof TaskTypeCOMPLETECUSTOMTASKS
> = z.nativeEnum(TaskTypeCOMPLETECUSTOMTASKS);

/** @internal */
export const TaskTypeCOMPLETECUSTOMTASKS$outboundSchema: z.ZodNativeEnum<
  typeof TaskTypeCOMPLETECUSTOMTASKS
> = TaskTypeCOMPLETECUSTOMTASKS$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskTypeCOMPLETECUSTOMTASKS$ {
  /** @deprecated use `TaskTypeCOMPLETECUSTOMTASKS$inboundSchema` instead. */
  export const inboundSchema = TaskTypeCOMPLETECUSTOMTASKS$inboundSchema;
  /** @deprecated use `TaskTypeCOMPLETECUSTOMTASKS$outboundSchema` instead. */
  export const outboundSchema = TaskTypeCOMPLETECUSTOMTASKS$outboundSchema;
}
