/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeINSTALLDEVICEMONITORING = {
  InstallDeviceMonitoring: "INSTALL_DEVICE_MONITORING",
} as const;
export type TaskTypeINSTALLDEVICEMONITORING = ClosedEnum<
  typeof TaskTypeINSTALLDEVICEMONITORING
>;

/** @internal */
export const TaskTypeINSTALLDEVICEMONITORING$inboundSchema: z.ZodNativeEnum<
  typeof TaskTypeINSTALLDEVICEMONITORING
> = z.nativeEnum(TaskTypeINSTALLDEVICEMONITORING);

/** @internal */
export const TaskTypeINSTALLDEVICEMONITORING$outboundSchema: z.ZodNativeEnum<
  typeof TaskTypeINSTALLDEVICEMONITORING
> = TaskTypeINSTALLDEVICEMONITORING$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskTypeINSTALLDEVICEMONITORING$ {
  /** @deprecated use `TaskTypeINSTALLDEVICEMONITORING$inboundSchema` instead. */
  export const inboundSchema = TaskTypeINSTALLDEVICEMONITORING$inboundSchema;
  /** @deprecated use `TaskTypeINSTALLDEVICEMONITORING$outboundSchema` instead. */
  export const outboundSchema = TaskTypeINSTALLDEVICEMONITORING$outboundSchema;
}
