/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The overall status of a person's outstanding tasks:
 *
 * @remarks
 * - NONE: There are no tasks.
 * - DUE_SOON: At least one task is due soon.
 * - OVERDUE: At least one task is overdue. Has a higher priority than DUE_SOON.
 * - COMPLETE: All tasks are complete.
 * - PAUSED: All tasks are paused.
 * - OFFBOARDING_DUE_SOON: At least one offboarding task is due soon.
 * - OFFBOARDING_OVERDUE: At least one offboarding task is overdue. Has a higher priority than OFFBOARDING_DUE_SOON.
 * - OFFBOARDING_COMPLETE: All offboarding tasks are complete.
 */
export const TasksSummaryStatus = {
  Complete: "COMPLETE",
  DueSoon: "DUE_SOON",
  None: "NONE",
  OffboardingComplete: "OFFBOARDING_COMPLETE",
  OffboardingDueSoon: "OFFBOARDING_DUE_SOON",
  OffboardingOverdue: "OFFBOARDING_OVERDUE",
  Overdue: "OVERDUE",
  Paused: "PAUSED",
} as const;
/**
 * The overall status of a person's outstanding tasks:
 *
 * @remarks
 * - NONE: There are no tasks.
 * - DUE_SOON: At least one task is due soon.
 * - OVERDUE: At least one task is overdue. Has a higher priority than DUE_SOON.
 * - COMPLETE: All tasks are complete.
 * - PAUSED: All tasks are paused.
 * - OFFBOARDING_DUE_SOON: At least one offboarding task is due soon.
 * - OFFBOARDING_OVERDUE: At least one offboarding task is overdue. Has a higher priority than OFFBOARDING_DUE_SOON.
 * - OFFBOARDING_COMPLETE: All offboarding tasks are complete.
 */
export type TasksSummaryStatus = ClosedEnum<typeof TasksSummaryStatus>;

/** @internal */
export const TasksSummaryStatus$inboundSchema: z.ZodNativeEnum<
  typeof TasksSummaryStatus
> = z.nativeEnum(TasksSummaryStatus);

/** @internal */
export const TasksSummaryStatus$outboundSchema: z.ZodNativeEnum<
  typeof TasksSummaryStatus
> = TasksSummaryStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TasksSummaryStatus$ {
  /** @deprecated use `TasksSummaryStatus$inboundSchema` instead. */
  export const inboundSchema = TasksSummaryStatus$inboundSchema;
  /** @deprecated use `TasksSummaryStatus$outboundSchema` instead. */
  export const outboundSchema = TasksSummaryStatus$outboundSchema;
}
