/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeACCEPTPOLICIES = {
  AcceptPolicies: "ACCEPT_POLICIES",
} as const;
export type TaskTypeACCEPTPOLICIES = ClosedEnum<typeof TaskTypeACCEPTPOLICIES>;

/** @internal */
export const TaskTypeACCEPTPOLICIES$inboundSchema: z.ZodNativeEnum<
  typeof TaskTypeACCEPTPOLICIES
> = z.nativeEnum(TaskTypeACCEPTPOLICIES);

/** @internal */
export const TaskTypeACCEPTPOLICIES$outboundSchema: z.ZodNativeEnum<
  typeof TaskTypeACCEPTPOLICIES
> = TaskTypeACCEPTPOLICIES$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskTypeACCEPTPOLICIES$ {
  /** @deprecated use `TaskTypeACCEPTPOLICIES$inboundSchema` instead. */
  export const inboundSchema = TaskTypeACCEPTPOLICIES$inboundSchema;
  /** @deprecated use `TaskTypeACCEPTPOLICIES$outboundSchema` instead. */
  export const outboundSchema = TaskTypeACCEPTPOLICIES$outboundSchema;
}
