/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type a task summary falls into.
 *
 * @remarks
 * COMPLETE_TRAININGS: The task summary containing security trainings.
 * ACCEPT_POLICIES: The task summary containing policy acceptance.
 * COMPLETE_CUSTOM_TASKS: The task summary containing custom tasks.
 * INSTALL_DEVICE_MONITORING: The task summary containing device monitoring installation.
 * COMPLETE_BACKGROUND_CHECKS: The task summary containing background checks.
 */
export const TaskType = {
  CompleteTrainings: "COMPLETE_TRAININGS",
  AcceptPolicies: "ACCEPT_POLICIES",
  CompleteCustomTasks: "COMPLETE_CUSTOM_TASKS",
  CompleteCustomOffboardingTasks: "COMPLETE_CUSTOM_OFFBOARDING_TASKS",
  InstallDeviceMonitoring: "INSTALL_DEVICE_MONITORING",
  CompleteBackgroundChecks: "COMPLETE_BACKGROUND_CHECKS",
} as const;
/**
 * The type a task summary falls into.
 *
 * @remarks
 * COMPLETE_TRAININGS: The task summary containing security trainings.
 * ACCEPT_POLICIES: The task summary containing policy acceptance.
 * COMPLETE_CUSTOM_TASKS: The task summary containing custom tasks.
 * INSTALL_DEVICE_MONITORING: The task summary containing device monitoring installation.
 * COMPLETE_BACKGROUND_CHECKS: The task summary containing background checks.
 */
export type TaskType = ClosedEnum<typeof TaskType>;

/** @internal */
export const TaskType$inboundSchema: z.ZodNativeEnum<typeof TaskType> = z
  .nativeEnum(TaskType);

/** @internal */
export const TaskType$outboundSchema: z.ZodNativeEnum<typeof TaskType> =
  TaskType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskType$ {
  /** @deprecated use `TaskType$inboundSchema` instead. */
  export const inboundSchema = TaskType$inboundSchema;
  /** @deprecated use `TaskType$outboundSchema` instead. */
  export const outboundSchema = TaskType$outboundSchema;
}
