/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The risk level of a vendor:
 *
 * @remarks
 * - CRITICAL: The vendor has a critical security risk
 * - HIGH: The vendor has a high security risk
 * - MEDIUM: The vendor has a medium security risk
 * - LOW: The vendor has a low security risk
 * - UNSCORED: The vendor has not been given a risk level
 */
export const VendorRiskLevel = {
  Critical: "CRITICAL",
  High: "HIGH",
  Low: "LOW",
  Medium: "MEDIUM",
  Unscored: "UNSCORED",
} as const;
/**
 * The risk level of a vendor:
 *
 * @remarks
 * - CRITICAL: The vendor has a critical security risk
 * - HIGH: The vendor has a high security risk
 * - MEDIUM: The vendor has a medium security risk
 * - LOW: The vendor has a low security risk
 * - UNSCORED: The vendor has not been given a risk level
 */
export type VendorRiskLevel = ClosedEnum<typeof VendorRiskLevel>;

/** @internal */
export const VendorRiskLevel$inboundSchema: z.ZodNativeEnum<
  typeof VendorRiskLevel
> = z.nativeEnum(VendorRiskLevel);

/** @internal */
export const VendorRiskLevel$outboundSchema: z.ZodNativeEnum<
  typeof VendorRiskLevel
> = VendorRiskLevel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VendorRiskLevel$ {
  /** @deprecated use `VendorRiskLevel$inboundSchema` instead. */
  export const inboundSchema = VendorRiskLevel$inboundSchema;
  /** @deprecated use `VendorRiskLevel$outboundSchema` instead. */
  export const outboundSchema = VendorRiskLevel$outboundSchema;
}
