/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * VulnerableAssetType describes the types of assets a vulnerability is on.
 */
export const VulnerableAssetType = {
  Server: "SERVER",
  ServerlessFunction: "SERVERLESS_FUNCTION",
  Container: "CONTAINER",
  ContainerRepository: "CONTAINER_REPOSITORY",
  ContainerRepositoryImage: "CONTAINER_REPOSITORY_IMAGE",
  CodeRepository: "CODE_REPOSITORY",
  ManifestFile: "MANIFEST_FILE",
  Workstation: "WORKSTATION",
} as const;
/**
 * VulnerableAssetType describes the types of assets a vulnerability is on.
 */
export type VulnerableAssetType = ClosedEnum<typeof VulnerableAssetType>;

/** @internal */
export const VulnerableAssetType$inboundSchema: z.ZodNativeEnum<
  typeof VulnerableAssetType
> = z.nativeEnum(VulnerableAssetType);

/** @internal */
export const VulnerableAssetType$outboundSchema: z.ZodNativeEnum<
  typeof VulnerableAssetType
> = VulnerableAssetType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VulnerableAssetType$ {
  /** @deprecated use `VulnerableAssetType$inboundSchema` instead. */
  export const inboundSchema = VulnerableAssetType$inboundSchema;
  /** @deprecated use `VulnerableAssetType$outboundSchema` instead. */
  export const outboundSchema = VulnerableAssetType$outboundSchema;
}
